//@ts-ignore
import type { Metadata } from "next";
import Header from '../components/header/main'
import s from './page.module.css'
import './global.css'
import { ReduxProvider } from "@/redux/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={s.body}>
        <ReduxProvider>
        <Header/>
        <main className={s.main}>
        {children}

        </main>
        </ReduxProvider>
        
      </body>
    </html>
  );
}
